INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (1, 'Laptop', 10, 99999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (2, 'Wireless Mechanical Keyboard', 45, 8999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (3, '27-inch Gaming Monitor', 15, 29999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (4, 'Ergonomic Vertical Mouse', 80, 3999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (5, 'USB-C Multi-Port Hub', 120, 2999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (6, 'Noise Canceling Headphones', 30, 14999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (7, 'Wireless Mechanical Keyboard - Tactile Switches', 45, 9999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (8, 'Ergonomic Vertical Mouse', 85, 4499) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (9, '34-inch UltraWide Curved Display', 12, 49999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (10, 'USB-C 11-in-1 Docking Station', 30, 7999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (11, 'Active Noise-Canceling Wireless Headphones', 60, 19999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (12, '1080p Full HD Webcam with Privacy Cover', 90, 4999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (13, 'Large Anti-Slip Desk Pad Mat (900x400mm)', 150, 1999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (14, 'Dual Monitor Mount Adjustable Arm', 25, 3999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (15, 'RGB Gaming Headset with Stand', 40, 5999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (16, '4K Ultra HD Streaming Camera', 18, 12999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (17, 'USB Microphone with Pop Filter', 55, 4999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (18, 'Ergonomic Mesh Office Chair with Lumbar Support', 15, 18999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (19, 'Electric Height Adjustable Standing Desk', 8, 29999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (20, 'Compact Aluminum Laptop Stand', 110, 2499) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (21, 'Magnetic Wireless Charger Stand (15W)', 75, 2999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (22, 'Bluetooth Portable Speaker Waterproof', 65, 3999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (23, '65W GaN Fast Charger Dual USB-C', 140, 3499) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (24, 'Braided USB-C to USB-C Cable 2m', 300, 1299) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (25, 'High-Speed HDMI 2.1 Cable 4K@120Hz', 220, 1499) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (26, 'Uninterruptible Power Supply (UPS) 1500VA', 10, 15999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (27, 'Cat 8 Ethernet Cable 10m High Speed', 180, 1899) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (28, 'Mechanical Keyboard Keycap Set - PBT', 50, 2999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (29, 'Desk LED Lamp with Wireless Charging Base', 35, 3999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (30, 'Smart Plug Wi-Fi Outlet Monitor', 95, 1499) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (31, 'External SSD Enclosure NVMe M.2', 70, 2499) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (32, '1TB Portable NVMe External SSD', 40, 8999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (33, '2TB High-Speed PCIe Gen4 NVMe Internal SSD', 30, 14999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (34, 'Wireless Presenter Clicker with Laser Pointer', 80, 1999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (35, 'Screenbar Monitor Light Bar Desk Lamp', 22, 4999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (36, 'Cable Management Box Set of 3', 130, 1999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (37, 'Foldable Bluetooth Pocket Keyboard', 28, 3499) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (38, 'Stylus Pen for Touchscreen Tablets', 105, 2999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (39, 'USB Graphics Drawing Tablet', 33, 5999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (40, 'Ultra-Thin Silent Wireless Mouse', 95, 1999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (41, 'Noise Isolating In-Ear Earbuds', 115, 1499) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (42, 'Computer Tower PC Dust Filter Cover', 210, 999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (43, 'Thermal Compound Paste for CPU/GPU', 175, 799) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (44, '120mm RGB PC Case Fan 3-Pack', 50, 2999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (45, '60% Mini RGB Mechanical Keyboard', 40, 5499) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (46, 'Wireless Gaming Controller for PC', 65, 3999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (47, 'Portable Monitor 15.6 Inch Full HD', 20, 11999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (48, 'Smart RGB LED Light Strip 5m', 85, 1999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (49, 'USB Flash Drive 128GB USB 3.2', 160, 1499) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (50, 'MicroSDXC Memory Card 256GB with Adapter', 140, 2499) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (51, 'Privacy Screen Filter for 15.6 Laptop', 45, 2999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (52, 'Vertical Laptop Stand Holder Double Slot', 60, 2499) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (53, 'Adjustable Footrest for Under Desk', 25, 2999) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (54, 'Blue Light Blocking Glasses for Screen Use', 120, 1599) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (55, 'Padded Wrist Rest Pad for Keyboard & Mouse', 85, 1299) ON CONFLICT(id) DO NOTHING;
INSERT INTO products (id, name, stock_quantity, amount_in_cents) VALUES (56, 'Surge Protector Power Strip 8 Outlets', 90, 2499) ON CONFLICT(id) DO NOTHING;
